import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "Woild" });

  return (
    <>
      <Head>
        <title>Friends</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <h1 className={styles.title}>
            Fri<span className={styles.pinkSpan}>ien</span>ds
          </h1>
          <p className={styles.showcaseText}>
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
      </main>
    </>
  );
};

export default Home;
